Removes clang 3.5.
Clang 3.5 has a bug, which ends in error messages like:

error: debug information for auto is not yet supported

Thus, we won't support clang 3.5